/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedArquivadosRouteImport } from './routes/_authenticated/arquivados'
import { Route as AuthenticatedCobrancasRouteImport } from './routes/_authenticated/cobrancas'
import { Route as AuthenticatedComercialRouteImport } from './routes/_authenticated/comercial'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFinalizadosRouteImport } from './routes/_authenticated/finalizados'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedLeadsArquivadosRouteImport } from './routes/_authenticated/leads-arquivados'
import { Route as AuthenticatedNovoRouteImport } from './routes/_authenticated/novo'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedPendentesRouteImport } from './routes/_authenticated/pendentes'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArquivadosRoute = AuthenticatedArquivadosRouteImport.update({
  id: '/arquivados',
  path: '/arquivados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCobrancasRoute = AuthenticatedCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComercialRoute = AuthenticatedComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinalizadosRoute =
  AuthenticatedFinalizadosRouteImport.update({
    id: '/finalizados',
    path: '/finalizados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsArquivadosRoute =
  AuthenticatedLeadsArquivadosRouteImport.update({
    id: '/leads-arquivados',
    path: '/leads-arquivados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovoRoute = AuthenticatedNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendentesRoute = AuthenticatedPendentesRouteImport.update({
  id: '/pendentes',
  path: '/pendentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/arquivados': typeof AuthenticatedArquivadosRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/finalizados': typeof AuthenticatedFinalizadosRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/leads-arquivados': typeof AuthenticatedLeadsArquivadosRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pendentes': typeof AuthenticatedPendentesRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/arquivados': typeof AuthenticatedArquivadosRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/finalizados': typeof AuthenticatedFinalizadosRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/leads-arquivados': typeof AuthenticatedLeadsArquivadosRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/pendentes': typeof AuthenticatedPendentesRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/arquivados': typeof AuthenticatedArquivadosRoute
  '/_authenticated/cobrancas': typeof AuthenticatedCobrancasRoute
  '/_authenticated/comercial': typeof AuthenticatedComercialRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/finalizados': typeof AuthenticatedFinalizadosRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/leads-arquivados': typeof AuthenticatedLeadsArquivadosRoute
  '/_authenticated/novo': typeof AuthenticatedNovoRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/pendentes': typeof AuthenticatedPendentesRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arquivados'
    | '/cobrancas'
    | '/comercial'
    | '/configuracoes'
    | '/equipe'
    | '/finalizados'
    | '/followups'
    | '/leads'
    | '/leads-arquivados'
    | '/novo'
    | '/orcamentos'
    | '/pendentes'
    | '/pipeline'
    | '/produtos'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/arquivados'
    | '/cobrancas'
    | '/comercial'
    | '/configuracoes'
    | '/equipe'
    | '/finalizados'
    | '/followups'
    | '/leads'
    | '/leads-arquivados'
    | '/novo'
    | '/orcamentos'
    | '/pendentes'
    | '/pipeline'
    | '/produtos'
    | '/vendas'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/arquivados'
    | '/_authenticated/cobrancas'
    | '/_authenticated/comercial'
    | '/_authenticated/configuracoes'
    | '/_authenticated/equipe'
    | '/_authenticated/finalizados'
    | '/_authenticated/followups'
    | '/_authenticated/leads'
    | '/_authenticated/leads-arquivados'
    | '/_authenticated/novo'
    | '/_authenticated/orcamentos'
    | '/_authenticated/pendentes'
    | '/_authenticated/pipeline'
    | '/_authenticated/produtos'
    | '/_authenticated/vendas'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arquivados': {
      id: '/_authenticated/arquivados'
      path: '/arquivados'
      fullPath: '/arquivados'
      preLoaderRoute: typeof AuthenticatedArquivadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cobrancas': {
      id: '/_authenticated/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof AuthenticatedCobrancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial': {
      id: '/_authenticated/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedComercialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finalizados': {
      id: '/_authenticated/finalizados'
      path: '/finalizados'
      fullPath: '/finalizados'
      preLoaderRoute: typeof AuthenticatedFinalizadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads-arquivados': {
      id: '/_authenticated/leads-arquivados'
      path: '/leads-arquivados'
      fullPath: '/leads-arquivados'
      preLoaderRoute: typeof AuthenticatedLeadsArquivadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novo': {
      id: '/_authenticated/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof AuthenticatedNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendentes': {
      id: '/_authenticated/pendentes'
      path: '/pendentes'
      fullPath: '/pendentes'
      preLoaderRoute: typeof AuthenticatedPendentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArquivadosRoute: typeof AuthenticatedArquivadosRoute
  AuthenticatedCobrancasRoute: typeof AuthenticatedCobrancasRoute
  AuthenticatedComercialRoute: typeof AuthenticatedComercialRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinalizadosRoute: typeof AuthenticatedFinalizadosRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLeadsArquivadosRoute: typeof AuthenticatedLeadsArquivadosRoute
  AuthenticatedNovoRoute: typeof AuthenticatedNovoRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPendentesRoute: typeof AuthenticatedPendentesRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArquivadosRoute: AuthenticatedArquivadosRoute,
  AuthenticatedCobrancasRoute: AuthenticatedCobrancasRoute,
  AuthenticatedComercialRoute: AuthenticatedComercialRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinalizadosRoute: AuthenticatedFinalizadosRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLeadsArquivadosRoute: AuthenticatedLeadsArquivadosRoute,
  AuthenticatedNovoRoute: AuthenticatedNovoRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPendentesRoute: AuthenticatedPendentesRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
